title: Po-Nan Li
description:  Po-Nan Li's personal homepage.
url: https://ponan.li
baseurl: ''
theme_skin: cardinal

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
